"""Type stubs for libdogecoin.

Covers the full ``w_*`` wrapper surface. Functions beyond the base
address/transaction set (BIP39/44, message signing, QR) are present only when
the package was built against a libdogecoin release that exports them; calling
one that is absent raises NotImplementedError at runtime. The stubs declare them
unconditionally so type-checking and autocomplete work regardless of build.
"""
from __future__ import annotations

from typing import Union, overload

_Str = Union[str, bytes]

# --- context ---------------------------------------------------------------
def w_context_start() -> None: ...
def w_context_stop() -> None: ...

# --- address / key ---------------------------------------------------------
@overload
def w_generate_priv_pub_key_pair(chain_code: int = ..., as_bytes: bool = ...) -> tuple[str, str]: ...
@overload
def w_generate_priv_pub_key_pair(chain_code: int, as_bytes: bool) -> tuple[bytes, bytes]: ...
@overload
def w_generate_hd_master_pub_key_pair(chain_code: int = ..., as_bytes: bool = ...) -> tuple[str, str]: ...
@overload
def w_generate_hd_master_pub_key_pair(chain_code: int, as_bytes: bool) -> tuple[bytes, bytes]: ...
def w_generate_derived_hd_pub_key(wif_privkey_master: _Str, as_bytes: bool = ...) -> Union[str, bytes]: ...
def w_verify_priv_pub_keypair(wif_privkey: _Str, p2pkh_pubkey: _Str, chain_code: int = ...) -> bool: ...
def w_verify_master_priv_pub_keypair(wif_privkey_master: _Str, p2pkh_pubkey_master: _Str, chain_code: int = ...) -> bool: ...
def w_verify_p2pkh_address(p2pkh_pubkey: _Str) -> bool: ...

# --- transaction (stateful working-tx table) -------------------------------
def w_start_transaction() -> int: ...
def w_add_utxo(tx_index: int, hex_utxo_txid: _Str, vout: int) -> int: ...
def w_add_output(tx_index: int, destination_address: _Str, amount: Union[str, int, float]) -> int: ...
def w_finalize_transaction(tx_index: int, destination_address: _Str, subtracted_fee: Union[str, int, float], out_dogeamount_for_verification: Union[str, int, float], changeaddress: _Str) -> Union[str, int]: ...
def w_get_raw_transaction(tx_index: int) -> Union[str, int]: ...
def w_clear_transaction(tx_index: int) -> None: ...
def w_sign_raw_transaction(tx_index: int, incoming_raw_tx: _Str, script_hex: _Str, sig_hash_type: int, privkey: _Str) -> Union[str, int]: ...
def w_sign_transaction(tx_index: int, script_pubkey: _Str, privkey: _Str) -> int: ...
def w_store_raw_transaction(incoming_raw_tx: _Str) -> int: ...
def w_remove_all() -> None: ...

# --- bip32 / bip44 (present on newer libdogecoin builds) -------------------
def w_get_derived_hd_address(masterkey: _Str, account: int, ischange: int, addressindex: int, outprivkey: bool = ...) -> str: ...
def w_get_derived_hd_address_by_path(masterkey: _Str, derived_path: _Str, outprivkey: bool = ...) -> str: ...

# --- bip39 (present on newer libdogecoin builds) ---------------------------
def w_generate_random_english_mnemonic(size: str) -> Union[str, None]: ...
def w_generate_english_mnemonic(entropy: _Str, size: str) -> Union[str, None]: ...
def w_dogecoin_seed_from_mnemonic(mnemonic: _Str, passphrase: _Str = ...) -> Union[bytes, None]: ...
def w_get_derived_hd_address_from_mnemonic(account: int, index: int, change_level: _Str, mnemonic: _Str, passphrase: _Str = ..., chain_code: int = ...) -> Union[str, None]: ...

# --- message signing (present on newer libdogecoin builds) -----------------
def w_sign_message(privkey: _Str, message: _Str) -> Union[str, None]: ...
def w_verify_message(signature: _Str, message: _Str, address: _Str) -> bool: ...

# --- qr (present on newer libdogecoin builds) ------------------------------
def w_qrgen_p2pkh_to_qr_string(p2pkh: _Str) -> Union[str, None]: ...
def w_qrgen_p2pkh_consoleprint_to_qr(p2pkh: _Str) -> None: ...
def w_qrgen_string_to_qr_pngfile(filename: _Str, data: _Str, size_multiplier: int = ...) -> int: ...
def w_qrgen_string_to_qr_jpgfile(filename: _Str, data: _Str, size_multiplier: int = ...) -> int: ...

# --- introspection ---------------------------------------------------------
def available() -> list[str]: ...
