"""Type stubs for libdogecoin.

Covers the full ``w_*`` wrapper surface and the Tier 3 object API. Functions
beyond the base address/transaction set (BIP39/44, message signing, QR, HD key
utilities) are present only when the package was built against a libdogecoin
release that exports them; calling one that is absent raises NotImplementedError
at runtime. The stubs declare them unconditionally so type-checking and
autocomplete work regardless of build.

The Tier 3 object API (``HDNode``, ``ChainParams``) is imported under
``_HAS_TIER3``; when False, those names are absent at runtime.
"""
from __future__ import annotations

from typing import Union, overload

_Str = Union[str, bytes]

# --- context ---------------------------------------------------------------
def w_context_start() -> None: ...
def w_context_stop() -> None: ...

# --- address / key ---------------------------------------------------------
@overload
def w_generate_priv_pub_key_pair(chain_code: int = ..., as_bytes: bool = ...) -> tuple[str, str]: ...
@overload
def w_generate_priv_pub_key_pair(chain_code: int, as_bytes: bool) -> tuple[bytes, bytes]: ...
@overload
def w_generate_hd_master_pub_key_pair(chain_code: int = ..., as_bytes: bool = ...) -> tuple[str, str]: ...
@overload
def w_generate_hd_master_pub_key_pair(chain_code: int, as_bytes: bool) -> tuple[bytes, bytes]: ...
def w_generate_derived_hd_pub_key(wif_privkey_master: _Str, as_bytes: bool = ...) -> Union[str, bytes]: ...
def w_verify_priv_pub_keypair(wif_privkey: _Str, p2pkh_pubkey: _Str, chain_code: int = ...) -> bool: ...
def w_verify_master_priv_pub_keypair(wif_privkey_master: _Str, p2pkh_pubkey_master: _Str, chain_code: int = ...) -> bool: ...
def w_verify_p2pkh_address(p2pkh_pubkey: _Str) -> bool: ...

# --- address / pubkey utilities (0.1.3+) -----------------------------------
def w_is_testnet_from_b58prefix(address: _Str) -> bool: ...
def w_is_mainnet_from_b58prefix(address: _Str) -> bool: ...
def w_get_address_from_pubkey(pubkey_hex: _Str, is_testnet: bool = ...) -> Union[str, None]: ...
def w_get_pubkey_from_privkey(privkey_wif: _Str, is_testnet: bool = ...) -> Union[str, None]: ...
def w_gen_privkey(is_testnet: bool = ...) -> Union[tuple[str, str], None]: ...
def w_dogecoin_address_to_pubkey_hash(p2pkh: _Str) -> Union[str, None]: ...
def w_dogecoin_private_key_wif_to_pubkey_hash(privkey_wif: _Str) -> Union[str, None]: ...
def w_dogecoin_p2pkh_address_to_pubkey_hash(p2pkh: _Str) -> Union[str, None]: ...
def w_get_addr_from_pubkey_hash(pubkey_hash: _Str, is_testnet: bool = ...) -> Union[str, None]: ...
def w_get_wif_encoded_privkey(privkey_hex: _Str, is_testnet: bool = ...) -> str: ...
def w_get_decoded_privkey_wif(privkey_wif: _Str, is_testnet: bool = ...) -> Union[str, None]: ...

# --- transaction (stateful working-tx table) -------------------------------
def w_start_transaction() -> int: ...
def w_add_utxo(tx_index: int, hex_utxo_txid: _Str, vout: int) -> int: ...
def w_add_output(tx_index: int, destination_address: _Str, amount: Union[str, int, float]) -> int: ...
def w_finalize_transaction(tx_index: int, destination_address: _Str, subtracted_fee: Union[str, int, float], out_dogeamount_for_verification: Union[str, int, float], changeaddress: _Str) -> Union[str, int]: ...
def w_get_raw_transaction(tx_index: int) -> Union[str, int]: ...
def w_clear_transaction(tx_index: int) -> None: ...
def w_sign_raw_transaction(tx_index: int, incoming_raw_tx: _Str, script_hex: _Str, sig_hash_type: int, privkey: _Str) -> Union[str, int]: ...
def w_sign_transaction(tx_index: int, script_pubkey: _Str, privkey: _Str) -> int: ...
def w_sign_transaction_w_privkey(tx_index: int, vout_index: int, privkey: _Str) -> int: ...
def w_store_raw_transaction(incoming_raw_tx: _Str) -> int: ...
def w_remove_all() -> None: ...

# --- bip32 / bip44 (present on newer libdogecoin builds) -------------------
def w_get_derived_hd_address(masterkey: _Str, account: int, ischange: int, addressindex: int, outprivkey: bool = ...) -> Union[str, None]: ...
def w_get_derived_hd_address_by_path(masterkey: _Str, derived_path: _Str, outprivkey: bool = ...) -> Union[str, None]: ...

# --- hd key utilities (0.1.3+) ---------------------------------------------
def w_get_hd_root_key_from_seed(seed_bytes: bytes, is_testnet: bool = ...) -> Union[str, None]: ...
def w_get_hd_pub_key(hdkey: _Str, is_testnet: bool = ...) -> Union[str, None]: ...
def w_derive_ext_key_from_hd_key(extkey: _Str, keypath: _Str, is_testnet: bool = ...) -> Union[str, None]: ...
def w_derive_ext_pub_key_from_hd_key(extpubkey: _Str, keypath: _Str, is_testnet: bool = ...) -> Union[str, None]: ...
def w_gen_hd_master(is_testnet: bool = ...) -> Union[str, None]: ...
def w_derive_hd_ext_from_master(masterkey: _Str, keypath: _Str, is_testnet: bool = ...) -> Union[str, None]: ...
def w_get_hd_node_privkey_wif_by_path(masterkey: _Str, derived_path: _Str, outprivkey: bool = ...) -> Union[str, None]: ...
def w_derive_bip44_extended_key(masterkey: _Str, account: Union[int, None], change_level: Union[str, int], address_index: Union[int, None], path: Union[str, None] = ..., is_testnet: bool = ...) -> Union[tuple[str, str], None]: ...
def w_derive_bip44_extended_public_key(masterkey: _Str, account: Union[int, None], change_level: Union[str, int], address_index: Union[int, None], path: Union[str, None] = ..., is_testnet: bool = ...) -> Union[tuple[str, str], None]: ...

# --- koinu utilities (0.1.3+) ----------------------------------------------
def w_koinu_to_coins_str(koinu: int) -> Union[str, None]: ...
def w_coins_to_koinu_str(coins: Union[str, int, float]) -> int: ...

# --- bip39 (present on newer libdogecoin builds) ---------------------------
def w_generate_random_english_mnemonic(size: str) -> Union[str, None]: ...
def w_generate_english_mnemonic(entropy: _Str, size: str) -> Union[str, None]: ...
def w_dogecoin_seed_from_mnemonic(mnemonic: _Str, passphrase: _Str = ...) -> Union[bytes, None]: ...
def w_get_derived_hd_address_from_mnemonic(account: int, index: int, change_level: _Str, mnemonic: _Str, passphrase: _Str = ..., chain_code: int = ...) -> Union[str, None]: ...
def w_dogecoin_verify_mnemonic(mnemonic: _Str, language: str = ..., space: str = ..., filename: Union[str, None] = ...) -> bool: ...

# --- message signing (present on newer libdogecoin builds) -----------------
def w_sign_message(privkey: _Str, message: _Str) -> Union[str, None]: ...
def w_verify_message(signature: _Str, message: _Str, address: _Str) -> bool: ...

# --- qr (present on newer libdogecoin builds) ------------------------------
def w_qrgen_p2pkh_to_qr_string(p2pkh: _Str) -> Union[str, None]: ...
def w_qrgen_p2pkh_consoleprint_to_qr(p2pkh: _Str) -> None: ...
def w_qrgen_string_to_qr_pngfile(filename: _Str, data: _Str, size_multiplier: int = ...) -> int: ...
def w_qrgen_string_to_qr_jpgfile(filename: _Str, data: _Str, size_multiplier: int = ...) -> int: ...

# --- transaction explicit-buffer variants (0.1.5+) -------------------------
def w_get_raw_transaction_ex(tx_index: int) -> Union[str, None]: ...
def w_finalize_transaction_ex(tx_index: int, destination_address: _Str, subtracted_fee: Union[str, int, float], out_dogeamount_for_verification: Union[str, int, float], changeaddress: _Str) -> Union[str, None]: ...
def w_sign_raw_transaction_ex(input_index: int, incoming_raw_tx: _Str, script_hex: _Str, sig_hash_type: int, privkey: _Str) -> Union[str, None]: ...
def w_sign_indexed_raw_transaction_ex(tx_index: int, input_index: int, script_hex: _Str, sig_hash_type: int, privkey: _Str) -> Union[str, None]: ...
def w_sign_transaction_ex(tx_index: int, script_pubkey: _Str, privkey: _Str) -> Union[str, None]: ...
def w_sign_transaction_w_privkey_ex(tx_index: int, privkey: _Str) -> Union[str, None]: ...

# --- introspection ---------------------------------------------------------
def available() -> list[str]: ...

# ---------------------------------------------------------------------------
# Tier 3 object API (present when _HAS_TIER3 is True)
# ---------------------------------------------------------------------------
_HAS_TIER3: bool

class HandleError(RuntimeError): ...
class UseAfterFreeError(HandleError): ...

class ChainParams:
    name: str
    def __init__(self, cptr: object, name: str) -> None: ...
    def __repr__(self) -> str: ...

MAINNET: ChainParams
TESTNET: ChainParams
REGTEST: ChainParams

class HDNode:
    depth: int
    fingerprint: int
    child_num: int
    chain_code: bytes
    private_key: bytes
    public_key: bytes
    closed: bool

    def __init__(self, ptr: object) -> None: ...
    @classmethod
    def new(cls) -> HDNode: ...
    @classmethod
    def from_seed(cls, seed: bytes) -> HDNode: ...
    @classmethod
    def deserialize(cls, extkey: str, chain: ChainParams) -> HDNode: ...
    def copy(self) -> HDNode: ...
    def derive_private(self, index: int) -> HDNode: ...
    def derive_public(self, index: int) -> HDNode: ...
    def fill_public_key(self) -> None: ...
    def serialize_public(self, chain: ChainParams) -> str: ...
    def serialize_private(self, chain: ChainParams) -> str: ...
    def pub_hex(self) -> str: ...
    def free(self) -> None: ...
    def __enter__(self) -> HDNode: ...
    def __exit__(self, *exc: object) -> None: ...
    def __repr__(self) -> str: ...
