/* AUTO-GENERATED from the fetched libdogecoin header. */
int chain_from_b58_prefix_bool(char* address);
void dogecoin_ecc_start(void);
void dogecoin_ecc_stop(void);
int isTestnetFromB58Prefix(char* address);
int isMainnetFromB58Prefix(char* address);
int generatePrivPubKeypair(char* wif_privkey, char* p2pkh_pubkey, int is_testnet);
int generateHDMasterPubKeypair(char* hd_privkey_master, char* p2pkh_pubkey_master, int is_testnet);
int generateDerivedHDPubkey(char* hd_privkey_master, char* p2pkh_pubkey);
int verifyPrivPubKeypair(char* wif_privkey, char* p2pkh_pubkey, int is_testnet);
int verifyHDMasterPubKeypair(char* hd_privkey_master, char* p2pkh_pubkey_master, int is_testnet);
int verifyP2pkhAddress(char* p2pkh_pubkey, size_t len);
int getDerivedHDAddress(char* masterkey, uint32_t account, int ischange, uint32_t addressindex, char* outaddress, int outprivkey);
int getDerivedHDAddressByPath(char* masterkey, char* derived_path, char* outaddress, int outprivkey);
int getAddressFromPubkey(char* pubkey_hex, int is_testnet, char* p2pkh_address);
int getPubkeyFromPrivkey(char* privkey_wif, int is_testnet, char* pubkey_hex, size_t* sizeout);
int genPrivkey(int is_testnet, char* privkey_wif, size_t strsize_wif, char* privkey_hex);
int dogecoin_p2pkh_address_to_pubkey_hash(char* p2pkh, char* scripthash);
char* dogecoin_address_to_pubkey_hash(char* p2pkh);
char* dogecoin_private_key_wif_to_pubkey_hash(char* private_key_wif);
int getAddrFromPubkeyHash(char* pubkey_hash, int is_testnet, char* p2pkh_address);
void getWifEncodedPrivKey(char* privkey, int is_testnet, char* privkey_wif, size_t* strsize_wif);
int getDecodedPrivKeyWif(char* privkey_wif, int is_testnet, char* privkey_hex);
int getHDRootKeyFromSeed(uint8_t* seed, const int seed_len, int is_testnet, char* masterkey);
int getHDPubKey(char* hdkey, int is_testnet, char* hdpubkey);
int deriveExtKeyFromHDKey(char* extkey, char* keypath, int is_testnet, char* key);
int deriveExtPubKeyFromHDKey(char* extpubkey, char* keypath, int is_testnet, char* pubkey);
int genHDMaster(int is_testnet, char* masterkey, size_t strsize);
int printNode(int is_testnet, char* nodeser);
int deriveHDExtFromMaster(int is_testnet, char* masterkey, char* keypath, char* extkeyout, size_t extkeyout_size);
char* getHDNodePrivateKeyWIFByPath(char* masterkey, char* derived_path, char* outaddress, int outprivkey);
int deriveBIP44ExtendedKey(char* hd_privkey_master, const uint32_t* account, char* change_level, const uint32_t* address_index, char* path, char* extkeyout, char* keypath);
int deriveBIP44ExtendedPublicKey(char* hd_privkey_master, const uint32_t* account, char* change_level, const uint32_t* address_index, char* path, char* extkeyout, char* keypath);
char* utils_uint8_to_hex(const uint8_t* bin, size_t l);
int generateEnglishMnemonic(char* entropy, char* size, char* mnemonic);
int generateRandomEnglishMnemonic(char* size, char* mnemonic);
int dogecoin_seed_from_mnemonic(char* mnemonic, char* pass, uint8_t* seed);
int getDerivedHDAddressFromMnemonic(const uint32_t account, const uint32_t index, char* change_level, char* mnemonic, char* pass, char* p2pkh_pubkey, int is_testnet);
int start_transaction(void);
int add_utxo(int txindex, char* hex_utxo_txid, int vout);
int add_output(int txindex, char* destinationaddress, char* amount);
char* finalize_transaction(int txindex, char* destinationaddress, char* subtractedfee, char* out_dogeamount_for_verification, char* changeaddress);
int sign_transaction(int txindex, char* script_pubkey, char* privkey);
int sign_transaction_w_privkey(int txindex, int vout_index, char* privkey);
void remove_all(void);
char* get_raw_transaction(int txindex);
void clear_transaction(int txindex);
int qrgen_p2pkh_to_qrbits(const char* in_p2pkh, uint8_t* outQrByteArray);
int qrgen_p2pkh_to_qr_string(const char* in_p2pkh, char* outString);
void qrgen_p2pkh_consoleprint_to_qr(char* in_p2pkh);
int qrgen_string_to_qr_pngfile(const char* outFilename, const char* inString, uint8_t sizeMultiplier);
int qrgen_string_to_qr_jpgfile(const char* outFilename, const char* inString, uint8_t sizeMultiplier);
int sign_raw_transaction(int inputindex, char* incomingrawtx, char* scripthex, int sighashtype, char* privkey);
int store_raw_transaction(char* incomingrawtx);
int koinu_to_coins_str(uint64_t koinu, char* str);
uint64_t coins_to_koinu_str(char* coins);
int start_key(void);
char* sign_message(char* privkey, char* msg);
int verify_message(char* sig, char* msg, char* address);
int dogecoin_unregister_watch_address_with_node(char* address);
int dogecoin_get_utxos_length(char* address);
char* dogecoin_get_utxo_txid_str(char* address, unsigned int index);
uint64_t dogecoin_get_balance(char* address);
char* dogecoin_get_balance_str(char* address);
