/* AUTO-GENERATED from the fetched libdogecoin header. */
void dogecoin_ecc_start(void);
void dogecoin_ecc_stop(void);
int generatePrivPubKeypair(char* wif_privkey, char* p2pkh_pubkey, int is_testnet);
int generateHDMasterPubKeypair(char* wif_privkey_master, char* p2pkh_pubkey_master, int is_testnet);
int generateDerivedHDPubkey(const char* wif_privkey_master, char* p2pkh_pubkey);
int verifyPrivPubKeypair(char* wif_privkey, char* p2pkh_pubkey, int is_testnet);
int verifyHDMasterPubKeypair(char* wif_privkey_master, char* p2pkh_pubkey_master, int is_testnet);
int verifyP2pkhAddress(char* p2pkh_pubkey, size_t len);
int getDerivedHDAddress(const char* masterkey, uint32_t account, int ischange, uint32_t addressindex, char* outaddress, int outprivkey);
int getDerivedHDAddressByPath(const char* masterkey, const char* derived_path, char* outaddress, int outprivkey);
int generateEnglishMnemonic(char* entropy, char* size, char* mnemonic);
int generateRandomEnglishMnemonic(char* size, char* mnemonic);
int dogecoin_seed_from_mnemonic(char* mnemonic, char* pass, uint8_t* seed);
int getDerivedHDAddressFromMnemonic(const uint32_t account, const uint32_t index, char* change_level, char* mnemonic, char* pass, char* p2pkh_pubkey, int is_testnet);
int start_transaction(void);
int add_utxo(int txindex, char* hex_utxo_txid, int vout);
int add_output(int txindex, char* destinationaddress, char* amount);
char* finalize_transaction(int txindex, char* destinationaddress, char* subtractedfee, char* out_dogeamount_for_verification, char* changeaddress);
int sign_transaction(int txindex, char* script_pubkey, char* privkey);
void remove_all(void);
char* get_raw_transaction(int txindex);
void clear_transaction(int txindex);
int qrgen_p2pkh_to_qrbits(const char* in_p2pkh, uint8_t* outQrByteArray);
int qrgen_p2pkh_to_qr_string(const char* in_p2pkh, char* outString);
void qrgen_p2pkh_consoleprint_to_qr(char* in_p2pkh);
int qrgen_string_to_qr_pngfile(const char* outFilename, const char* inString, uint8_t sizeMultiplier);
int qrgen_string_to_qr_jpgfile(const char* outFilename, const char* inString, uint8_t sizeMultiplier);
int sign_raw_transaction(int inputindex, char* incomingrawtx, char* scripthex, int sighashtype, char* privkey);
int store_raw_transaction(char* incomingrawtx);
char* dogecoin_char_vla(size_t size);
void dogecoin_free(void* ptr);
int start_key(void);
char* sign_message(char* privkey, char* msg);
int verify_message(char* sig, char* msg, char* address);
